--- # webserver
server:
  port: 8080
  context-path: /

--- # logging
logging:
  level:
#    org.springframework.web.servlet.mvc: debug
#    org.mybatis: debug

--- # datasource
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 1
    maximum-pool-size: 10
    connection-timeout: 5000

mybatis:
  config-location: classpath:mybatis-config.xml #增加mybatis xml风格的支持
  mapper-locations: classpath:mapper/*.xml